project:
  type: website
  render:
    - "*.qmd"
    - "!CHANGELOG.md"
    - "!data/"

website:
  title: "Nisace's website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
